version: '3'

services:
  postgres:
    image: postgres:11.12
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql11:/var/log/postgresql
      - postgresql11:/var/lib/postgresql
    restart: unless-stopped

  sigtrans:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigtrans
    depends_on:
      - postgres
    environment:
      #Sem o DATABASE_URL não conseguia encontrar o banco de dados, e não pode ser @localhost
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgresql11:
    driver: local
